name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      # Managed by bors
      - auto
  # Run nightly checks to detect possible breakage due to upstream rustc changes
  schedule:
    - cron: '0 0 * * *'

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
        - toolchain: x86_64-unknown-linux-gnu
          builder: ubuntu-latest
          os: linux
        - toolchain: x86_64-apple-darwin
          builder: macos-latest
          os: macos
        - toolchain: x86_64-pc-windows-msvc
          builder: windows-latest
          os: windows

    name: nightly - ${{ matrix.toolchain }}
    runs-on: ${{ matrix.builder }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup latest nightly toolchain
        run: bash ci/setup-toolchain.sh
        if: github.event_name == 'schedule'
      - name: Run tests
        run: sh ci/run.sh ${{ matrix.os }}

  # https://forge.rust-lang.org/infra/docs/bors.html#adding-a-new-repository-to-bors
  build_result:
    name: bors build finished
    runs-on: ubuntu-latest
    needs: ["build_and_test"]
    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
